import type { AnySpotMockState } from './types'

export const initialMockState: AnySpotMockState = {
  users: [
    {
      id: 'usr_mila',
      name: 'Mila Novak',
      email: 'mila@anyspot.demo',
      role: 'user',
      creditsBalance: 18,
    },
    {
      id: 'usr_reception',
      name: 'Reception Desk',
      email: 'frontdesk@studio.demo',
      role: 'reception',
      creditsBalance: 0,
    },
    {
      id: 'usr_manager',
      name: 'Studio Manager',
      email: 'manager@studio.demo',
      role: 'management',
      creditsBalance: 0,
    },
    {
      id: 'usr_admin',
      name: 'Marketplace Admin',
      email: 'admin@anyspot.demo',
      role: 'admin',
      creditsBalance: 0,
    },
    {
      id: 'usr_superadmin',
      name: 'Founder Control',
      email: 'founder@anyspot.demo',
      role: 'superadmin',
      creditsBalance: 0,
    },
  ],
  gyms: [
    {
      id: 'gym_pulse',
      name: 'Pulse Studio Karlin',
      city: 'Prague',
      status: 'active',
      monthlyBookings: 348,
      payoutDueCzk: 79840,
    },
    {
      id: 'gym_core',
      name: 'Core House Brno',
      city: 'Brno',
      status: 'active',
      monthlyBookings: 214,
      payoutDueCzk: 48620,
    },
    {
      id: 'gym_nova',
      name: 'Nova Barre',
      city: 'Prague',
      status: 'pending',
      monthlyBookings: 0,
      payoutDueCzk: 0,
    },
  ],
  classes: [
    {
      id: 'cls_ignite',
      gymId: 'gym_pulse',
      title: 'Ignite Strength',
      trainer: 'Tereza',
      startsAt: 'Today, 18:00',
      capacity: 18,
      bookedCount: 15,
      creditsRequired: 4,
      status: 'scheduled',
    },
    {
      id: 'cls_reformer',
      gymId: 'gym_core',
      title: 'Reformer Flow',
      trainer: 'Adam',
      startsAt: 'Tomorrow, 08:30',
      capacity: 10,
      bookedCount: 8,
      creditsRequired: 5,
      status: 'scheduled',
    },
    {
      id: 'cls_barre',
      gymId: 'gym_nova',
      title: 'Barre Foundations',
      trainer: 'Lucie',
      startsAt: 'Friday, 17:30',
      capacity: 14,
      bookedCount: 4,
      creditsRequired: 3,
      status: 'scheduled',
    },
  ],
  bookings: [
    {
      id: 'book_001',
      userId: 'usr_mila',
      classId: 'cls_ignite',
      customerName: 'Mila Novak',
      checkedIn: false,
      status: 'confirmed',
    },
    {
      id: 'book_002',
      userId: 'usr_mila',
      classId: 'cls_reformer',
      customerName: 'Mila Novak',
      checkedIn: true,
      status: 'completed',
    },
  ],
  payouts: [
    {
      id: 'pay_001',
      gymId: 'gym_pulse',
      amountCzk: 79840,
      period: 'May 1-14',
      status: 'scheduled',
    },
    {
      id: 'pay_002',
      gymId: 'gym_core',
      amountCzk: 48620,
      period: 'May 1-14',
      status: 'processing',
    },
  ],
  auditEvents: [
    {
      id: 'audit_001',
      actor: 'Founder Control',
      action: 'Seeded MVP workspace with mock operating data',
      createdAt: 'Just now',
    },
  ],
  platformSettings: {
    transactionFeePercent: 0,
    monthlySubscriptionCzk: 2490,
    firstTenGymsFreeMonths: 3,
    redisCachePlanned: true,
  },
}
